### ISSUE TITLE
Error: (SystemJS) [BABEL] unknown: Unknown option: direct.0 	ReferenceError: [BABEL] unknown: Unknown option: direct.0

### ISSUE THREAD

**Issue by Mohankumarj** [angular/material-start#170]

**Comment by Mohankumarj** [comment]
Hi, help me to work,
i Clone the latest version of Master and install npm, jspm, and run the live-server, lite-server,ng serve everything shows me the same error in the brower.

i cloned this link too https://github.com/angular/material-start/tree/es6-tutorial

same error.

**Comment by AndrewBarfield** [comment]
I'm getting the same on Ubuntu 16.10 / Chrome 57:

`Live reload enabled.
Error: (SystemJS) [BABEL] unknown: Unknown option: direct.0
	ReferenceError: [BABEL] unknown: Unknown option: direct.0
	    at Logger.error (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:8955:11)
	    at OptionManager.mergeOptions (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:9463:29)
	    at OptionManager.init (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:9553:10)
	    at File.initOptions (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:8193:75)
	    at new File (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:8183:22)
	    at Pipeline.transform (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:13515:16)
	Error loading http://localhost:8080/src/boot/boot.js
	    at Logger.error (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:8955:11)
	    at OptionManager.mergeOptions (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:9463:29)
	    at OptionManager.init (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:9553:10)
	    at File.initOptions (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:8193:75)
	    at new File (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:8183:22)
	    at Pipeline.transform (http://localhost:8080/jspm_packages/npm/babel-core@5.8.38/browser.js:13515:16)
	Error loading http://localhost:8080/src/boot/boot.js
`

**Comment by HabibeC** [comment]
+1

**Comment by gregor-srdic** [comment]
+1

**Comment by MahmoudHboubati** [comment]
+1

**Comment by EladBezalel** [comment]
Hey, I've tried to reproduce this issue, i re-cloned the repo, freshly installed `jspm` and everything seems to work.

Can any of you please note the steps that lead you to this issue?

**Comment by congkhuong** [comment]
+1

**Comment by umbria** [comment]
+1

**Comment by EladBezalel** [comment]
What version of node are you using? of jspm? i couldn't reproduce..

**Comment by umbria** [comment]
I'm using v6.10.2

**Comment by EliKrumholz** [comment]
+1

**Comment by pbov** [comment]
@EliKrumholz works, thank you!

Maybe this should be fixed, not working examples are not fun

**Comment by Gennady77** [comment]
+

**Comment by denisacostaq** [comment]
Fixed by @angelomichel on #165 👍 the PR still unmerged.
