### ISSUE TITLE
"bower update" always failed when extracting bower-angular-animate

### ISSUE THREAD

**Issue by jianwu-github** [angular/material-start#51]
> material-start@0.0.2 postinstall /Users/jianwu/angularjs/gitrepos/material-start
> bower update

bower angular-animate#^1.4.x       not-cached git://github.com/angular/bower-angular-animate.git#^1.4.x
bower angular-animate#^1.4.x          resolve git://github.com/angular/bower-angular-animate.git#^1.4.x
bower angular#^1.4.x                   cached git://github.com/angular/bower-angular.git#1.4.3
bower angular#^1.4.x                 validate 1.4.3 against git://github.com/angular/bower-angular.git#^1.4.x
bower angular-material#~0.9.4          cached git://github.com/angular/bower-material.git#0.9.8
bower angular-material#~0.9.4        validate 0.9.8 against git://github.com/angular/bower-material.git#~0.9.4
bower angular-aria#^1.4.x              cached git://github.com/angular/bower-angular-aria.git#1.4.3
bower angular-aria#^1.4.x            validate 1.4.3 against git://github.com/angular/bower-angular-aria.git#^1.4.x
bower angular-animate#^1.4.x         download https://github.com/angular/bower-angular-animate/archive/v1.4.3.tar.gz
bower angular-animate#^1.4.x          extract archive.tar.gz
bower angular-animate#^1.4.x           EACCES EACCES, rename '/var/folders/z7/zt2wlkbj59z3k0vxs3f9182r0000gn/T/jianwu/bower/angular-animate-7238-bPBCB5'

Stack trace:
Error: EACCES, rename '/var/folders/z7/zt2wlkbj59z3k0vxs3f9182r0000gn/T/jianwu/bower/angular-animate-7238-bPBCB5'

Console trace:
Error
    at StandardRenderer.error (/Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/bin/bower:110:22)
    at Logger.EventEmitter.emit (events.js:95:17)
    at Logger.emit (/Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/node_modules/q/q.js:844:24)
    at /Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/node_modules/q/q.js:788:41)
    at /Users/jianwu/angularjs/gitrepos/material-start/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.10.28
OS: Darwin 14.0.0 x64

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.28
npm ERR! npm  v2.13.4
npm ERR! code ELIFECYCLE
npm ERR! material-start@0.0.2 postinstall: `bower update`
npm ERR! Exit status 1

**Comment by MaxFlower** [comment]
Update bower. Now latest release: v1.7.2. And after that clear cache for bower (http://bower.io/docs/api/#cache).
