### ISSUE TITLE
Errors running `jspm install`

### ISSUE THREAD

**Issue by dmitriz** [angular/material-start#84]
Any hint how to fix that?
```sh
± |es6 ✗| → jspm install

err  TypeError: Install of css to ^0.1.6 has no registry property provided.
         at /Users/dmitrizaitsev/Repos/material-start/node_modules/jspm/lib/package.js:309:13
         at Array.forEach (native)
         at processDeps (/Users/dmitrizaitsev/Repos/material-start/node_modules/jspm/lib/package.js:292:21)
         at setDefaults (/Users/dmitrizaitsev/Repos/material-start/node_modules/jspm/lib/config/package.js:128:25)
         at PackageJSON.read (/Users/dmitrizaitsev/Repos/material-start/node_modules/jspm/lib/config/package.js:116:3)
         at /Users/dmitrizaitsev/Repos/material-start/node_modules/jspm/lib/config.js:80:25
         at process._tickCallback (node.js:368:9)
         at Function.Module.runMain (module.js:469:11)
         at startup (node.js:136:18)
         at node.js:963:3

warn Installation changes not saved.
```

**Comment by ThomasBurleson** [comment]
could not reproduce.
